import os
import socket

RPC_URL = os.environ.get("RPC_URL", "http://127.0.0.1:8332")
RPC_USER = os.environ.get("RPC_USER", "replace")
RPC_PASS = os.environ.get("RPC_PASS", "replace")
DEBUGGING = os.environ.get("DEBUGGING", "False")
WORKER = os.environ.get("WORKER", socket.gethostname())
CENTRAL_MN_IP = os.environ.get("CENTRAL_MN_IP", "127.0.0.1")
CENTRAL_MN_PORT = int(os.environ.get("CENTRAL_MN_PORT", 19201))
MSG_BIND_PORT = int(os.environ.get("MSG_BIND_PORT", 29291))
GPUECM_SERVER_IP = os.environ.get("GPUECM_SERVER_IP", "")
GPUECM_SERVER_PORT = os.environ.get("GPUECM_SERVER_PORT", "19302")
CUDAECM_SERVER_IP = os.environ.get("CUDAECM_SERVER_IP", "")
CUDAECM_MAX_LEVEL = int(os.environ.get("CUDAECM_MAX_LEVEL", 4))
MINER_MODE = os.environ.get("MINER_MODE", "SERVER")
CADO_SERVER_URL = os.environ.get("CADO_SERVER_URL", "")
CADO_CLIENT_BASE_PATH = os.environ.get("CADO_CLIENT_BASE_PATH", "/tmp")
MSG_SERVER_IP = os.environ.get("MSG_SERVER_IP", "")
NAT_MASTER_URL = os.environ.get("NAT_MASTER_URL", "nats://localhost:4222")
if MSG_SERVER_IP == "" and CADO_SERVER_URL != "":
    cado_servers = CADO_SERVER_URL.split()
    cado_servers = cado_servers[0].split(':')
    MSG_SERVER_IP = cado_servers[1].replace("//", "")
MSG_SERVER_PORT = int(os.environ.get("MSG_SERVER_PORT", 29291))
FIRST_ACCEPT_LEVEL = int(os.environ.get("FIRST_ACCEPT_LEVEL", 4))
SECOND_ACCEPT_LEVEL = int(os.environ.get("SECOND_ACCEPT_LEVEL", 4))
THIRD_ACCEPT_LEVEL = int(os.environ.get("THIRD_ACCEPT_LEVEL", 4))
ECM_ONLY = os.environ.get("ECM_ONLY", "False")
YAFU_ONLY = os.environ.get("YAFU_ONLY", "False")
DUAL_MINING_CHECK_PROCESS = os.environ.get("DUAL_MINING_CHECK_PROCESS", "")
FARM_GROUP = os.environ.get("FARM_GROUP", "Default")
MINER_GROUP = os.environ.get("MINER_GROUP", "")
MN_BROKER = os.environ.get("MN_BROKER", "")
W_MUL_INTERVAL = int(os.environ.get("W_MUL_INTERVAL", 12))
if W_MUL_INTERVAL < 1:
    W_MUL_INTERVAL = 1
if W_MUL_INTERVAL > 16:
    W_MUL_INTERVAL = 16
SORT_SEED = os.environ.get("SORT_SEED", "False")
CADO_CLIENT_THREAD_COUNT = int(os.environ.get("CADO_CLIENT_THREAD_COUNT", 2))
POLY_CLIENT_THREAD_COUNT = int(os.environ.get("POLY_CLIENT_THREAD_COUNT", CADO_CLIENT_THREAD_COUNT))
USE_MSIEVE = os.environ.get("USE_MSIEVE", "False")
SENTENCE_IN_CADO_NFS_FOR_STOPPING_PROCESS = os.environ.get("SENTENCE_IN_CADO_NFS_FOR_STOPPING_PROCESS", "")
USE_DUAL_PROCESS = os.environ.get("USE_DUAL_PROCESS", "False")
USE_GCD_PROCESS = os.environ.get("USE_GCD_PROCESS", "True")
STOP_CADO_PROCESS_WITH_DUAL = os.environ.get("STOP_CADO_PROCESS_WITH_DUAL", "True")
MAX_SIEVE_LEVEL = int(os.environ.get("MAX_SIEVE_LEVEL", 28))
WALLET_ADDRESS = os.environ.get("WALLET_ADDRESS", "")
CHECK_CANDIDATE_WITH_CUDA_ECM = os.environ.get("CHECK_CANDIDATE_WITH_CUDA_ECM", "")
USE_MINER_ECM = os.environ.get("USE_MINER_ECM", "True")
USE_YAFU_ECM = os.environ.get("USE_YAFU_ECM", "False")
ECM_BIND_PORT = int(os.environ.get("ECM_BIND_PORT", 19300))
ECM_STEP_OF_CANDIDATE_SIEVING = int(os.environ.get("ECM_STEP_OF_CANDIDATE_SIEVING", 6))
MAX_MSIEVE_COUNT = int(os.environ.get("MAX_MSIEVE_COUNT", 2))
MSIEVE_DIR_NAME = os.environ.get("MSIEVE_DIR_NAME", "/msieve_nfsathome")
PRE_GET_POLY = os.environ.get("PRE_GET_POLY", "False")
DISPLAY_MESSAGES = os.environ.get("DISPLAY_MESSAGES", "")
